alias .="z ."
alias ..="z .."
alias ls="exa -al --color=always --group-directories-first --icons --group"
alias cat="bat --style header --style rules --style snip --style changes"
alias grep="rg --color=auto"
alias sed="sed -E"
alias tree="tree -CSAFah"
alias mv="mv -i"
alias rm="rm -i"
